name: SSH into AWS Instance

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: SSH into AWS Instance
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ip-172-31-39-242 'ls -l'
