name: Create a text file in EC2 instance
on:
  push:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@ec2-3-108-61-131.ap-south-1.compute.amazonaws.com
      - name: Create text file
        run: |
          echo "This is a text file" > /home/ubuntu/new_file.txt
