name: SSH Action

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  ssh-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure SSH
      uses: webfactory/ssh-agent@v0.5.2
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-key-name: "github-actions-key"  # Replace with your chosen identifier

    - name: Run remote command
      run: ssh ${{ secrets.SSH_USERNAME }} "echo Hello from remote server"
