name: SSH Action

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  ssh-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run remote command
      run: |
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@ec2-3-108-61-131.ap-south-1.compute.amazonaws.com "echo 'Hello from remote server'"
